const rusCountries = {
  "Afghanistan": "Афганистан",
  "Albania": "Албания",
  "Algeria": "Алжир",
  "Andorra": "Андорра",
  "Angola": "Ангола",
  "Anguilla": "Ангилья",
  "Antigua and Barbuda": "Антигуа и Барбуда",
  "Argentina": "Аргентина",
  "Armenia": "Армения",
  "Aruba": "Аруба",
  "Australia": "Австралия",
  "Austria": "Австрия",
  "Azerbaijan": "Азербайджан",
  "Bahamas": "Багамские острова",
  "Bahrain": "Бахрейн",
  "Bangladesh": "Бангладеш",
  "Barbados": "Барбадос",
  "Belarus": "Беларусь",
  "Belgium": "Бельгия",
  "Belize": "Белиз",
  "Benin": "Бенин",
  "Bermuda": "Бермудские острова",
  "Bhutan": "Бутан",
  "Bolivia": "Боливия",
  "Bosnia and Herzegovina": "Босния и Герцеговина",
  "Botswana": "Ботсвана",
  "Brazil": "Бразилия",
  "British Virgin Islands": "Британские Виргинские острова",
  "Brunei": "Бруней",
  "Bulgaria": "Болгария",
  "Burkina Faso": "Буркина-Фасо",
  "Burundi": "Бурунди",
  "Cabo Verde": "Кабо Верде",
  "Cambodia": "Камбоджа",
  "Cameroon": "Камерун",
  "Canada": "Канада",
  "CAR": "Центральноафриканская Республика",
  "Caribbean Netherlands": "Карибские Нидерланды",
  "Cayman Islands": "Каймановы острова",
  "Chad": "Чад",
  "Channel Islands": "Нормандские острова",
  "Chile": "Чили",
  "China": "Китай",
  "Colombia": "Колумбия",
  "Congo": "Конго",
  "Costa Rica": "Коста-Рика",
  "Croatia": "Хорватия",
  "Cuba": "Куба",
  "Curaçao": "Кюрасао",
  "Cyprus": "Кипр",
  "Czechia": "Чехия",
  "Denmark": "Дания",
  "Diamond Princess": "Бриллиантовая принцесса",
  "Djibouti": "Джибути",
  "Dominica": "Доминика",
  "Dominican Republic": "Доминиканская Республика",
  "DRC": "Демократическая Республика Конго",
  "Ecuador": "Эквадор",
  "Egypt": "Египет",
  "El Salvador": "Эль Сальвадор",
  "Equatorial Guinea": "Экваториальная Гвинея",
  "Eritrea": "Эритрея",
  "Estonia": "Эстония",
  "Eswatini": "Эсватини",
  "Ethiopia": "Эфиопия",
  "Faeroe Islands": "Фарерские острова",
  "Falkland Islands": "Фолклендские острова",
  "Fiji": "Фиджи",
  "Finland": "Финляндия",
  "France": "Франция",
  "French Guiana": "Французская Гвиана",
  "French Polynesia": "Французская Полинезия",
  "Gabon": "Габон",
  "Gambia": "Гамбия",
  "Georgia": "Грузия",
  "Germany": "Германия",
  "Ghana": "Гана",
  "Gibraltar": "Гибралтар",
  "Greece": "Греция",
  "Greenland": "Гренландия",
  "Grenada": "Гренада",
  "Guadeloupe": "Гваделупа",
  "Guatemala": "Гватемала",
  "Guinea": "Гвинея",
  "Guinea-Bissau": "Гвинея-Бисау",
  "Guyana": "Гайана",
  "Haiti": "Гаити",
  "Honduras": "Гондурас",
  "Hong Kong": "Гонконг",
  "Hungary": "Венгрия",
  "Iceland": "Исландия",
  "India": "Индия",
  "Indonesia": "Индонезия",
  "Iran": "Иран",
  "Iraq": "Ирак",
  "Ireland": "Ирландия",
  "Isle of Man": "Остров Мэн",
  "Israel": "Израиль",
  "Italy": "Италия",
  "Ivory Coast": "Кот-д'Ивуар",
  "Jamaica": "Ямайка",
  "Japan": "Япония",
  "Jordan": "Иордания",
  "Kazakhstan": "Казахстан",
  "Kenya": "Кения",
  "Kuwait": "Кувейт",
  "Kyrgyzstan": "Кыргызстан",
  "Laos": "Лаос",
  "Latvia": "Латвия",
  "Lebanon": "Ливан",
  "Liberia": "Либерия",
  "Libya": "Ливия",
  "Liechtenstein": "Лихтенштейн",
  "Lithuania": "Литва",
  "Luxembourg": "Люксембург",
  "Macao": "Макао",
  "Madagascar": "Мадагаскар",
  "Malawi": "Малави",
  "Malaysia": "Малайзия",
  "Maldives": "Мальдивы",
  "Mali": "Мали",
  "Malta": "Мальта",
  "Martinique": "Мартиника",
  "Mauritania": "Мавритания",
  "Mauritius": "Маврикий",
  "Mayotte": "Майотта",
  "Mexico": "Мексика",
  "Moldova": "Молдова",
  "Monaco": "Монако",
  "Mongolia": "Монголия",
  "Montenegro": "Черногория",
  "Montserrat": "Монтсеррат",
  "Morocco": "Марокко",
  "Mozambique": "Мозамбик",
  "MS Zaandam": "Лайнер Zaandam",
  "Myanmar": "Мьянма",
  "Namibia": "Намибия",
  "Nepal": "Непал",
  "Netherlands": "Нидерланды",
  "New Caledonia": "Новая Каледония",
  "New Zealand": "Новая Зеландия",
  "Nicaragua": "Никарагуа",
  "Niger": "Нигер",
  "Nigeria": "Нигерия",
  "North Macedonia": "Северная Македония",
  "Norway": "Норвегия",
  "Oman": "Оман",
  "Pakistan": "Пакистан",
  "Palestine": "Палестина",
  "Panama": "Панама",
  "Papua New Guinea": "Папуа - Новая Гвинея",
  "Paraguay": "Парагвай",
  "Peru": "Перу",
  "Philippines": "Филиппины",
  "Poland": "Польша",
  "Portugal": "Португалия",
  "Qatar": "Катар",
  "Romania": "Румыния",
  "Russia": "Россия",
  "Rwanda": "Руанда",
  "Réunion": "Реюньон",
  "S. Korea": "Южная Корея",
  "Saint Kitts and Nevis": "Сент-Китс и Невис",
  "Saint Lucia": "Санкт-Люсия",
  "Saint Martin": "Святой Мартин",
  "Saint Pierre Miquelon": "Сен-Пьер Микелон",
  "San Marino": "Сан-Марино",
  "Sao Tome and Principe": "Сан-Томе и Принсипи",
  "Saudi Arabia": "Саудовская Аравия",
  "Senegal": "Сенегал",
  "Serbia": "Сербия",
  "Seychelles": "Сейшельские Острова",
  "Sierra Leone": "Сьерра-Леоне",
  "Singapore": "Сингапур",
  "Sint Maarten": "Синт-Мартен",
  "Slovakia": "Словакия",
  "Slovenia": "Словения",
  "Somalia": "Сомали",
  "South Africa": "Южная Африка",
  "South Sudan": "Южный Судан",
  "Spain": "Испания",
  "Sri Lanka": "Шри-Ланка",
  "St. Barth": "Сен-Барт",
  "St. Vincent Grenadines": "Сент-Винсент Гренадины",
  "Sudan": "Судан",
  "Suriname": "Суринам",
  "Sweden": "Швеция",
  "Switzerland": "Швейцария",
  "Syria": "Сирия",
  "Taiwan": "Тайвань",
  "Tanzania": "Танзания",
  "Thailand": "Таиланд",
  "Timor-Leste": "Тимор-Лешти",
  "Togo": "Того",
  "Trinidad and Tobago": "Тринидад и Тобаго",
  "Tunisia": "Тунис",
  "Turkey": "Турция",
  "Turks and Caicos": "Теркс и Кайкос",
  "UAE": "ОАЭ",
  "Uganda": "Уганда",
  "UK": "Великобритания ",
  "Ukraine": "Украина",
  "Uruguay": "Уругвай",
  "USA": "США",
  "Uzbekistan": "Узбекистан",
  "Vatican City": "Ватикан",
  "Venezuela": "Венесуэла",
  "Vietnam": "Вьетнам",
  "Western Sahara": "Западная Сахара",
  "Yemen": "Йемен",
  "Zambia": "Замбия",
  "Zimbabwe": "Зимбабве"
}



















